#!/usr/bin/env bash
# This script updates /etc/hosts to set localhost to
# 127.0.0.2 and facebook.com to 8.8.8.8

sudo sed -i '/127\.0\.0\.1\s\+/localhost/d' /etc/hosts
sudo sed -i '/facebook\.com/d' /etc/hosts

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
