#!/bin/bash
# Configure Ubuntu server so that:
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8

cp /etc/hosts /etc/hosts.bak

sed -i 's/127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2 localhost/' /etc/hosts

grep -q "facebook.com" /etc/hosts && \
    sed -i 's/.*facebook\.com.*/8.8.8.8 facebook.com/' /etc/hosts || \
    echo "8.8.8.8 facebook.com" >> /etc/hosts
    